In [42]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix 


In [3]:
data = pd.read_csv("D:\\Data Science\\Assignment\\Assignment 6\\bankfull.csv")
data.head(11)

age      job marital  education default  balance housing loan    contact  \
0    18  student  single  secondary      no      156      no   no   cellular   
1    18  student  single    primary      no      608      no   no   cellular   
2    18  student  single    unknown      no      108      no   no   cellular   
3    18  student  single    primary      no     1944      no   no  telephone   
4    18  student  single    unknown      no       35      no   no  telephone   
5    18  student  single  secondary      no        5      no   no   cellular   
6    18  student  single    unknown      no      438      no   no   cellular   
7    18  student  single    unknown      no      108      no   no   cellular   
8    18  student  single    primary      no      608      no   no   cellular   
9    18  student  single    unknown      no        3      no   no   cellular   
10   18  student  single    unknown      no      108      no   no   cellular   

    day month  duration  campaign  pdays  previous poutcome    y  
0     4   nov       298         2     82         4    other   no  
1    13   nov       210         1     93         1  success  yes  
2     9   feb        92         1    183         1  success  yes  
3    10   aug       122         3     -1         0  unknown   no  
4    21   aug       104         2     -1         0  unknown   no  
5    24   aug       143         2     -1         0  unknown   no  
6     1   sep       425         1     -1         0  unknown   no  
7    10   aug       167         1     -1         0  unknown  yes  
8    12   aug       267         1     -1         0  unknown  yes  
9    25   aug       130         2     -1         0  unknown  yes  
10    8   sep       169         1     -1         0  unknown  yes

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [9]:
data.tail()

age      job   marital  education default  balance housing loan  \
45206   93  retired   married    unknown      no      775      no   no   
45207   93  retired   married    unknown      no      775      no   no   
45208   94  retired  divorced  secondary      no     1234      no   no   
45209   95  retired  divorced    primary      no     2282      no   no   
45210   95  retired   married  secondary      no        0      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
45206   cellular   22   jul       860         2    177         7  success  yes  
45207   cellular    4   aug       476         2     13         9  success  yes  
45208   cellular    3   mar       212         1     -1         0  unknown   no  
45209  telephone   21   apr       207        17     -1         0  unknown  yes  
45210  telephone    1   oct       215         1     -1         0  unknown   no

In [10]:
data.drop(columns=['housing'], inplace=True, axis=0 )

In [11]:
data.head()

age      job marital  education default  balance loan    contact  day  \
0   18  student  single  secondary      no      156   no   cellular    4   
1   18  student  single    primary      no      608   no   cellular   13   
2   18  student  single    unknown      no      108   no   cellular    9   
3   18  student  single    primary      no     1944   no  telephone   10   
4   18  student  single    unknown      no       35   no  telephone   21   

  month  duration  campaign  pdays  previous poutcome    y  
0   nov       298         2     82         4    other   no  
1   nov       210         1     93         1  success  yes  
2   feb        92         1    183         1  success  yes  
3   aug       122         3     -1         0  unknown   no  
4   aug       104         2     -1         0  unknown   no

In [25]:
x1 = data.iloc[:,0:15]
y = data.iloc[: ,15:16]


In [34]:
x = pd.get_dummies(x1, columns=['job','marital','education','poutcome','default','loan','month','contact'])

In [44]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.3,shuffle=True)



In [45]:
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

c:\Users\heysr\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\heysr\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
classifier.intercept_


array([-0.36698206])

In [40]:
classifier.coef_

array([[-1.10419908e-02,  2.42946468e-05, -1.01891914e-02,
         3.74795502e-03, -3.83893749e-01,  2.08245626e-03,
        -1.75070288e-01, -3.68354725e-02, -3.38164655e-01,
        -3.56668465e-02, -1.01214195e-02,  1.12735202e-02,
         2.17938223e-01, -2.00128397e-02, -1.17712770e-01,
         4.30999404e-02, -9.01085477e-02,  5.43632174e-03,
         3.92717903e-03,  1.89177193e-02, -2.30938317e-01,
        -1.54926769e-01, -9.26582904e-02, -3.58764845e-01,
         6.53075479e-02,  1.91682207e-02, -1.77085116e-01,
        -4.07394525e-02,  4.07567883e-01, -5.56690682e-01,
        -3.41032643e-01, -2.59147239e-02, -1.08096047e-01,
        -2.58851320e-01,  4.88189927e-02,  4.33372831e-02,
         3.78933594e-02, -1.54759986e-02, -1.53213215e-02,
        -1.04257551e-01, -6.59717203e-02,  1.13482462e-01,
        -5.62347553e-01, -7.55590175e-02,  1.29863720e-01,
         9.85899776e-02,  1.26602428e-01,  6.84730738e-02,
        -5.62022868e-01]])

In [47]:
y_train_pred = classifier.predict(x_train)
ac = (y_train,y_train_pred)
print(ac)


(         y
5264   yes
32702   no
12639   no
13191   no
3158    no
...    ...
32386   no
21246   no
38312   no
42747   no
12433  yes

[31647 rows x 1 columns], array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object))


In [48]:
y_test_pred = classifier.predict(x_test)
ac = (y_test_pred,y_test)
print(ac)

(array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object),          y
14205   no
19879   no
37372   no
15468   no
40399   no
...    ...
30640  yes
29282   no
9490    no
7833    no
10884   no

[13564 rows x 1 columns])


In [53]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as accuracy_score
conf_matrix = confusion_matrix(y_train, y_train_pred)
accuracy = accuracy_score(y_train, y_train_pred)
print(conf_matrix)


[[27538   390]
 [ 3150   569]]
0.8881410560242677


In [54]:
print(accuracy)

0.8881410560242677


In [57]:
from sklearn.metrics import classification_report
print(classification_report(y_train, y_train_pred))


              precision    recall  f1-score   support

          no       0.90      0.99      0.94     27928
         yes       0.59      0.15      0.24      3719

    accuracy                           0.89     31647
   macro avg       0.75      0.57      0.59     31647
weighted avg       0.86      0.89      0.86     31647

